### ISSUE TITLE
Bowden lip

### ISSUE THREAD

**Issue by rlaferla** [Eytecz/LGX_Lite_Stealthburner_CW2_style_mount#2]
It seems like we need to remove the Bowden lip to use this mount.  Is this true?  If so, do we re-insert it on the mount hole?

<img width="228" alt="image" src="https://user-images.githubusercontent.com/1135694/155600695-90db792a-5e1c-44e3-ac5e-c9752cac06c3.png">

**Comment by Eytecz** [comment]
Hi, the clip that it was designed for is a bit more rigid than the standard clip delivered with the LGX Lite. This style clip is to be used: https://nl.aliexpress.com/item/32896103430.html

And yes, you need to remove the clip in the LGX Lite itself. The bowden tube is fixed by the printed part a bit higher up.

It is mostly already delivered with a lot of hotends, you might already have one laying around :)
